const actionTypes = {
  SIGNUP: "SIGNUP",
  LOGIN: "LOGIN",
  LOGINFAIL: "LOGINFAIL",
  SIGNUPFAIL: "SIGNUPFAIL",
  SIGNUPSUCCESS: "SIGNUPSUCCESS",
  ADDPRODUCTSUCCESS: "ADDPRODUCTSUCCESS",
  ADDPRODUCTFAIL: "ADDPRODUCTFAIL"
};

export default actionTypes;
